name: zip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: zip
      run: |
        for file in ./*
        do
          zip -r ./${file}/${file}.zip ${file}
        done
    - name: list files
      run:
        ls -R
    - name: commit
      run: |
        git config --global user.name "harkerhand"
        git config --global user.email "harkerhand@outlook.com"
        git add .
        git commit -m "zip" -a
    - name: push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
