name: zip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip
      run:
        echo "Zip Begin"
        cd .
        for file in ./*
        do
            cd ./"${file}"
            zip -r ./"${file}".zip .
            cd ..
        done
        
        echo "Zip End"
    - name: List files
      run:
        ls -R
        
