name: zip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip
      run:
        for file in ./*;do zip -r ./${file}/${file}.zip ${file};done
    - name: List files
      run:
        ls -R
        
