name: zip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip
      run:
        echo "Zip Begin"
        
        for file in *
        do
            zip -r ${file}"/"${file}.zip ${file}
        done
        
        echo "Zip End"
    - name: List files
      run:
        ls -R
        
