name: zip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip
      run:
        zip -r 001/001.zip 001
        zip -r 002/002.zip 001
    - name: List files
      run:
        ls -R
        
