name: zip

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Zip
      run:
        cd .
        zip -r 001.zip 001
        for file in ./*
        do
          cd ./"${file}"
          zip -r ./"${file}".zip .
          cd ..
        done
    - name: List files
      run:
        ls -R
        
